### ISSUE TITLE
Add new tasking to help easily support different databases out of the box

### ISSUE THREAD

**Issue by GitBytes** [pacifica/ansible-pacifica#30]
https://github.com/pacifica/ansible-pacifica/blob/bd78e4491b71f23f151ee18a98d205e3f7ef011e/tasks/pip.yml#L2

I think there is a way we can create or utilize list of packages for different types of DB backends and change to the appropriate list of pip packages with the flip of a default value. In addition, I think as a "default" we should settle on using the postgresql variant (including psycopg2 pip package ootb).

**Comment by dmlb2000** [comment]
The way to do this is to set the `aux_pkg` key in the service name in the `pacifica_avaialable_services` variable for the playbook. This is complicated and I'd like to have a better solution (I'm thinking about this).

So something like the following variables should be set:
```
pacifica_available_services:
  metadata:
    aux_pkg:
      - pymysql
      - redis
      - amqp
      - psycopg2
...
```
The `aux_pkg` list would need to be repeated for every available service to that node, where ever you want the variable set.

I've avoided trying to set database libraries as default since some platforms have issues trying to use them from PyPI. Some systems seem to configure cleaner using the system installed psycopg2, like:

https://github.com/pacifica/ansible-pacifica/blob/8c04354c4b9c3bce5363ffd400fffdd1bc10a308/molecule/common/allinone-converge.yml.j2#L71

Where other systems need to install `psycopg2-binary` to work better.

So, the only solution I see to this issue is to create a molecule scenario with MySQL as a backend alternative instead of PostgreSQL. Does that seem reasonable?
